// SPDX-License-Identifier: Unlicense
pragma solidity ^0.8.17;

import "./TinySig.sol";

contract solve {
    // ejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglsuejgliurjgslrigjhlsiuerghlureshgslrukghsluerhguisrhglsureighlsirughslruighiurlghlsiruhgslirhglsirughsleihgrlusihgleriughsleighrsleughslrugihslriughslriughslriughslirhgsleriughsliruhgslihgrughsrlieughslirghslrghslruehglsriuhglusirehlfiurehfuirehsgiurnlierjgioughmvciyrgushergiuhnsvkgumdkicurgkiuergskrhgskrubgksgsejrbnvksrbcmuerbscnukmtnktgshclreughncsnrekigumskurjmxgbksrefbsmkixrmhgsmkierumghmsxkiruchgscmelflagiufhskirghskrghskueghseuirghsuirhgsuirhguhrgurehgushrlushlreughslurhgsluihglsuiehrglsuihrgsuirhgslruhglsuierhgsuiehgrughslurhgslirhglsuirhglejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglejfiejfiejfiejfiejfiejfiejfijfeijfiefjieaaaaaaaaaaaaaaaaa
    mapping(address => bytes32) private aeaowign;

    function ejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglsuejgliurjgslrigjhlsiuerghlureshgslrukghsluerhguisrhglsureighlsirughslruighiurlghlsiruhgslirhglsirughsleihgrlusihgleriughsleighrsleughslrugihslriughslriughslriughslirhgsleriughsliruhgslihgrughsrlieughslirghslrghslruehglsriuhglusirehlfiurehfuirehsgiurnlierjgioughmvciyrgushergiuhnsvkgumdkicurgkiuergskrhgskrubgksgsejrbnvksrbcmuerbscnukmtnktgshclreughncsnrekigumskurjmxgbksrefbsmkixrmhgsmkierumghmsxkiruchgscmelflagiufhskirghskrghskueghseuirghsuirhgsuirhguhrgurehgushrlushlreughslurhgsluihglsuiehrglsuihrgsuirhgslruhglsuierhgsuiehgrughslurhgslirhglsuirhglejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglejfiejfiejfiejfiejfiejfiejfijfeijfiefjiejfiejfiejfiejfiejifjieidnsdglejfiejfiejfiejfiejfiejfiejfijfeijfiefjieaaaaaaaaaaaaaaaaa(bytes32 _hifh) external {
        aeaowign[msg.sender] = _hifh;
    }

    fallback(bytes calldata) external returns(bytes memory eorkeorkeokroekroekroekroe) {
        eorkeorkeokroekroekroekroe = abi.encode(
            aeaowign[tx.origin],
            uint8(28),
            bytes32(0x00000000000000000000003b78ce563f89a0ed9414f5aa28ad0d96d6795f9c63)
        );
    }
}